### ISSUE TITLE
crash, might be related to the mod

### ISSUE THREAD

**Issue by pibblepower** [Spazley/ScalingGUIs#1]
when I run a large modpack with this installed, it crashes and it says this mod is involved. could this be fixed
[crash-2021-12-06_08.50.22-client.txt](https://github.com/Spazley/ScalingGUIs/files/7661187/crash-2021-12-06_08.50.22-client.txt)
?

**Comment by Spazley** [comment]
Fixed in v1.12.2-1.0.3.1.  Thanks to Srdjan-V.
